SELECT DISTINCT
    CLASS.TERM_CD,
    CLASS.SESSION_CD,
    CLASS.UF_COURSE_NUMBER,
    CLASS.CLASS_NUM,
    CLASS.CLASS_DESC,
    CLASS.CLASS_STATUS_CD,
    CLASS.HONORS_FLAG,
    CLASS.UFO_FLAG,
    CLASS.TOT_ENRLMT,
    CLASS.ENRLMT_CAP,
    CLASS.ENRLMT_CAP-CLASS.TOT_ENRLMT AS "SEATS_LEFT",
    CLASS.QUEST1_FLAG
FROM
    PUB_STUDENT_RECORDS_AND_FINANCIAL_AID.DATA_VENDING.WH_D_CLASS CLASS
        INNER JOIN PUB_STUDENT_RECORDS_AND_FINANCIAL_AID.DATA_VENDING.WH_D_TERM TERM ON 
            TERM.TERM_SID = CLASS.TERM_SID
WHERE 1=1
    AND CLASS.CLASS_STATUS_CD IN ('A','S')
    AND CLASS.TERM_CD IN ('2255','2258')
    AND CLASS.QUEST1_FLAG = 'Y'